dataset_path: "/home/schnakes/beegfs/Ele_FixedAngle_processed/"
raw_dataset_path: "/home/schnakes/beegfs/Ele_FixedAngle/"
num_workers: 40
batch_size: 32
lr: 1e-3
model_type: "PointFlow" # "AE" "VAE" "PointFlow"


point_means: [25.6793, 25.5028, 15.4454, -3.8321]
point_stds: [5.1746, 4.7922, 5.7521, 1.8171]
e_hat_mean: 0.9691
e_hat_std: 0.0815
n_hat_mean: 107.76
n_hat_std: 8.2153

encoder:
  in_features: 4
  latent_dim: 256
  point_layers: [8, 16, 32, 64, 128, 256]
  latent_layers: [256, 256, 256, 256]

latent_flow:
  features: 258
  n_transforms: 4
  tail_bound: 5.
  num_bins: 8
  context_features: 1
  context_hidden_features: 32
  hidden_features: 64
  num_blocks: 2
  


point_flow:
  features: 4
  n_transforms: 8
  tail_bound: 6.
  num_bins: 12
  context_features: 258
  context_hidden_features: 64
  hidden_features: 64
  num_blocks: 8
  

trainer:
  accelerator: "gpu"
  devices: -1
  max_epochs: 1000
  #detect_anomaly: true
  strategy: "ddp"
  # log_every_n_steps: 100
  num_sanity_val_steps: 0
  # accumulate_grad_batches: 128
  # profiler: "simple"
