path:
  base: "/beegfs/desy/user/schnakes/"
  raw: "hadrons_better_faster_stronger_pions/"
  train: "pion_train_uniform"
  eval: "pion_eval_uniform"
  eval_step: "pion_eval_steps20to90"
  raw_file_end: ".hdf5"


data:
  base_path: "/home/schnakes/beegfs/hadrons_better_faster_stronger_pions/"
  train: "pion_train_uniform"
  eval: "pion_eval_uniform"
  eval_step: "pion_eval_steps20to90"
  energy_key: "hcal_only/energy"
  shower_key: "hcal_only/layers"
